### ISSUE TITLE
Image path

### ISSUE THREAD

**Issue by jaromir-sukuba** [patex1987/BullsCowsGui#1]
Image path is invalid when building in Linux. Please change from
`self.bull_icon = tk.PhotoImage(file=r'.\img\Cultures-Bull-icon.png')`
to 
`self.bull_icon = tk.PhotoImage(file=r'img/Cultures-Bull-icon.png')`
The same applies for second picture.

**Comment by patex1987** [comment]
Solved! Check this commit: https://github.com/patex1987/BullsCowsGui/commit/f07c157ffd77ec0c048103c952c130a34b731d13
